#ifndef __IMG_TEST_IMAGES_H
#define __IMG_TEST_IMAGES_H

#include "lcd.h"

Color Img_GreenBlock_10x10[10][10] = {
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN},
	{GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN}
};

Color Img_None_1x1[1][1] = {0x0000};

Color Img_RedBlock_4x4[4][4] = {
	{RED, RED, RED, RED},
	{RED, RED, RED, RED},
	{RED, RED, RED, RED},
	{RED, RED, RED, RED}
};

#endif